"""Reusable Power BI-style UI components.

Title band, slicer bar, KPI cards, tiles, insight strip, cross-filter charts,
drill-through tables and Customer 360.
"""

from __future__ import annotations

import html
import re
from collections.abc import Iterator, Sequence
from contextlib import contextmanager
from datetime import date, timedelta

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from app import data, kpis
from app.state import SLICERS, Filters, current_filters, init_state, reset_filters, toggle_filter
from app.theme import (
    BAD,
    CSS,
    DECISION_COLORS,
    GOOD,
    MUTED,
    TEAL,
    TILE,
    fmt_days,
    fmt_int,
    fmt_pct,
)

CHART_CONFIG = {"displayModeBar": False, "responsive": True}
SIM_NOTE = (
    "SIMULATED: opened/closed dates, channel, analyst, turnaround and SLA are generated by a seeded "
    "simulation (seed 42) because the source has no timestamps. See Model and method."
)
PRESETS = {"All": None, "Last 12 months": 365, "Last 6 months": 182, "Last 3 months": 91}
CUSTOMER_ID_RE = re.compile(r"^C\d{6}$")


def inject_css() -> None:
    """Apply the design-system CSS once per run."""
    st.markdown(CSS, unsafe_allow_html=True)


def sim_pill() -> str:
    """HTML for the purple SIMULATED pill."""
    return '<span class="sim-pill" title="Derived from the seeded simulation, not from source data">SIMULATED</span>'


def real_pill() -> str:
    """HTML for the teal 'dataset' pill marking visuals computed from the real synthetic dataset."""
    return '<span class="real-pill" title="Computed from the source dataset">DATASET</span>'


# ---------------------------------------------------------------------------
# Slicers
# ---------------------------------------------------------------------------
def _sync(name: str) -> None:
    st.session_state[f"flt_{name}"] = list(st.session_state.get(f"w_{name}", []))


def _sync_dates() -> None:
    value = st.session_state.get("w_dates")
    if isinstance(value, (tuple, list)) and len(value) == 2:
        st.session_state["flt_dates"] = (value[0], value[1])


def _apply_preset(full_start: date, full_end: date) -> None:
    days = PRESETS.get(st.session_state.get("w_preset") or "All")
    if days is None:
        st.session_state["flt_dates"] = (full_start, full_end)
    else:
        st.session_state["flt_dates"] = (max(full_start, full_end - timedelta(days=days - 1)), full_end)


def _preset_for(dates: tuple[date, date], full_start: date, full_end: date) -> str:
    for label, days in PRESETS.items():
        start = full_start if days is None else max(full_start, full_end - timedelta(days=days - 1))
        if dates == (start, full_end):
            return label
    return "Custom"


def slicer_bar() -> Filters:
    """Render the report-level slicer bar and return the active filters."""
    full_start, full_end = data.date_bounds()
    init_state(full_start, full_end)
    with st.container(key="slicer_bar"):
        cols = st.columns([1.2, 1.6, 1, 1, 1, 1.1, 1.2, 1.0], vertical_alignment="bottom")
        st.session_state["w_preset"] = _preset_for(tuple(st.session_state["flt_dates"]), full_start, full_end)
        cols[0].selectbox(
            "Period",
            [*PRESETS, "Custom"],
            key="w_preset",
            on_change=_apply_preset,
            args=(full_start, full_end),
        )
        st.session_state["w_dates"] = tuple(st.session_state["flt_dates"])
        cols[1].date_input(
            "Opened date (SIMULATED)",
            key="w_dates",
            min_value=full_start,
            max_value=full_end,
            on_change=_sync_dates,
            format="YYYY-MM-DD",
        )
        for col, (name, (column, label)) in zip(cols[2:7], SLICERS.items(), strict=True):
            st.session_state[f"w_{name}"] = list(st.session_state[f"flt_{name}"])
            col.multiselect(
                label,
                data.distinct_values(column),
                key=f"w_{name}",
                on_change=_sync,
                args=(name,),
                placeholder="All",
            )
        cols[7].button(
            "Reset filters",
            key="reset_filters",
            help="All slicers back to All",
            on_click=reset_filters,
            args=(full_start, full_end),
            width="stretch",
            icon=":material/filter_alt_off:",
        )
    filters = current_filters(full_start, full_end)
    active = filters.active_count(full_start, full_end)
    if active:
        st.caption(f"{active} slicer(s) active — applied to every sliceable visual on every page.")
    return filters


def page_header(title: str, question: str, simulated: bool = False, slicers: bool = True) -> Filters | None:
    """Title band, optional SIMULATED pill and the slicer bar."""
    inject_css()
    pills = real_pill() + (sim_pill() if simulated else "")
    st.markdown(
        f'<div class="title-band"><div><h1>{html.escape(title)}</h1>'
        f'<div class="question">{html.escape(question)}</div></div>'
        f'<div>{pills}<span class="sim-pill" style="background:#5F6B6D">SYNTHETIC DATA</span></div></div>',
        unsafe_allow_html=True,
    )
    return slicer_bar() if slicers else None


def insight_strip(sentences: Sequence[str]) -> None:
    """Render 2-3 computed insight sentences under the page title."""
    items = "".join(f"<li>{html.escape(s)}</li>" for s in sentences if s)
    st.markdown(f'<div class="insight-strip"><ul>{items}</ul></div>', unsafe_allow_html=True)


def headline(text: str) -> None:
    """Prominent headline-finding banner."""
    st.markdown(f'<div class="headline">{text}</div>', unsafe_allow_html=True)


def flat_badge(text: str, flat: bool) -> None:
    """Red 'FLAT' notice above a chart whose groups do not differ meaningfully."""
    if flat:
        st.markdown(
            f'<div style="color:{BAD};font-weight:700;font-size:12px">{html.escape(text)}</div>', unsafe_allow_html=True
        )


def footnote(text: str) -> None:
    """Small grey footnote."""
    st.markdown(f'<div class="footnote">{html.escape(text)}</div>', unsafe_allow_html=True)


# ---------------------------------------------------------------------------
# KPI cards and tiles
# ---------------------------------------------------------------------------
def kpi_card(
    key: str,
    label: str,
    value: str,
    delta: float | None = None,
    polarity: int = 1,
    simulated: bool = False,
    foot: str = "",
) -> None:
    """Power BI-style KPI card with a coloured, arrowed delta (never colour alone)."""
    if delta is None:
        delta_html = f'<span class="kpi-delta" style="color:{MUTED}">vs prior period: n/a</span>'
    else:
        good = (delta >= 0) == (polarity >= 0) if delta != 0 else True
        arrow = "▲" if delta > 0 else ("▼" if delta < 0 else "■")
        color = GOOD if good else BAD
        word = "better" if good else "worse"
        delta_html = (
            f'<span class="kpi-delta" style="color:{color}">{arrow} {abs(delta):.1%} vs prior period ({word})</span>'
        )
    pill = sim_pill() if simulated else ""
    with st.container(key=f"kpi_{key}"):
        st.markdown(
            f'<div class="kpi-label">{html.escape(label)}{pill}</div>'
            f'<div class="kpi-value">{html.escape(value)}</div>{delta_html}'
            f'<div class="kpi-foot">{html.escape(foot)}</div>',
            unsafe_allow_html=True,
        )


@contextmanager
def tile(key: str, title: str, subtitle: str = "", simulated: bool = False) -> Iterator[None]:
    """White bordered tile with a title, optional subtitle and SIMULATED pill."""
    with st.container(key=f"tile_{key}"):
        pill = sim_pill() if simulated else ""
        st.markdown(
            f'<div class="tile-title">{html.escape(title)}{pill}</div>'
            + (f'<div class="tile-sub">{html.escape(subtitle)}</div>' if subtitle else ""),
            unsafe_allow_html=True,
        )
        yield
        if simulated:
            footnote(SIM_NOTE)


def chart(fig: go.Figure, key: str, height: int = 300) -> None:
    """Render a non-interactive Plotly chart with the shared config."""
    fig.update_layout(height=height, template="kyc_pbi", paper_bgcolor=TILE, plot_bgcolor=TILE)
    st.plotly_chart(fig, key=key, width="stretch", config=CHART_CONFIG, theme=None)


def xf_chart(fig: go.Figure, key: str, slicer: str, height: int = 300) -> None:
    """Render a chart whose clicks cross-filter every page.

    Each clickable trace must carry the slicer value in ``customdata[0]``.
    Clicking the only selected value clears the filter (Power BI behaviour).
    """
    fig.update_layout(
        height=height, clickmode="event+select", template="kyc_pbi", paper_bgcolor=TILE, plot_bgcolor=TILE
    )
    nonce = st.session_state.get("xf_nonce", 0)
    event = st.plotly_chart(
        fig,
        key=f"xf_{key}_{nonce}",
        on_select="rerun",
        selection_mode="points",
        width="stretch",
        config=CHART_CONFIG,
        theme=None,
    )
    points = event.selection.points if event and event.selection else []
    if points:
        custom = points[0].get("customdata")
        value = custom[0] if isinstance(custom, (list, tuple)) and custom else custom
        if value is not None:
            toggle_filter(slicer, str(value))
            st.session_state["xf_nonce"] = nonce + 1
            st.rerun()
    st.caption(f"Click a mark to cross-filter by {SLICERS[slicer][1].lower()}; click it again to clear.")


def donut(labels: Sequence[str], values: Sequence[float], colors: Sequence[str], center: str) -> go.Figure:
    """Build a selectable donut from dense scatter markers on a ring.

    Plotly pie slices do not emit selection events in Streamlit, so the ring is
    built from markers (which do) to support click-to-cross-filter.
    """
    fig = go.Figure()
    total = float(sum(values)) or 1.0
    start = 0.0
    for label, value, color in zip(labels, values, colors, strict=True):
        span = value / total * 360
        n = max(int(span * 1.5), 2)
        pad = min(0.4, span / 4)
        theta = np.radians(90 - np.linspace(start + pad, start + span - pad, n))
        fig.add_trace(
            go.Scatter(
                x=np.cos(theta),
                y=np.sin(theta),
                mode="markers",
                name=f"{label} ({value / total:.1%})",
                marker=dict(size=26, color=color, line=dict(width=0)),
                customdata=[[label]] * n,
                hovertemplate=f"<b>{html.escape(label)}</b><br>{value:,.0f} cases ({value / total:.1%})<extra></extra>",
            )
        )
        start += span
    fig.update_xaxes(visible=False, range=[-1.45, 1.45], fixedrange=True)
    fig.update_yaxes(visible=False, range=[-1.3, 1.3], scaleanchor="x", fixedrange=True)
    fig.update_layout(
        showlegend=True,
        legend=dict(orientation="v", x=1.0, y=0.5, xanchor="left", yanchor="middle"),
        annotations=[dict(text=center, x=0, y=0, showarrow=False, font=dict(size=15))],
        dragmode=False,
        margin=dict(l=0, r=0, t=0, b=0),
    )
    return fig


def decision_bar_colors(decisions: Sequence[str]) -> list[str]:
    """Return the fixed decision colours for a list of decisions."""
    return [DECISION_COLORS.get(d, MUTED) for d in decisions]


# ---------------------------------------------------------------------------
# Tables, drill-through and export
# ---------------------------------------------------------------------------
def tidy(frame: pd.DataFrame) -> pd.DataFrame:
    """Display copy: dates without times (months as YYYY-MM)."""
    out = frame.copy()
    for col in out.columns:
        if pd.api.types.is_datetime64_any_dtype(out[col]):
            fmt = "%Y-%m" if col.endswith("month") else "%Y-%m-%d"
            out[col] = out[col].dt.strftime(fmt)
    return out


def table(frame: pd.DataFrame, **kwargs: object) -> None:
    """st.dataframe with tidy dates and thousands separators on numeric columns."""
    shown = tidy(frame)
    config: dict = {}
    for col in shown.columns:
        if pd.api.types.is_integer_dtype(shown[col]) and not col.startswith(("rank", "stage_order")):
            config[col] = st.column_config.NumberColumn(format="localized")
    config.update(kwargs.pop("column_config", None) or {})  # type: ignore[arg-type]
    kwargs.setdefault("hide_index", True)
    kwargs.setdefault("width", "stretch")
    st.dataframe(shown, column_config=config, **kwargs)  # type: ignore[arg-type]


def case_table(frame: pd.DataFrame, key: str, height: int = 320) -> None:
    """Case table where clicking a row opens Customer 360 in a dialog (drill-through)."""
    nonce_key = f"dt_nonce_{key}"
    nonce = st.session_state.get(nonce_key, 0)
    event = st.dataframe(
        tidy(frame),
        key=f"dt_{key}_{nonce}",
        on_select="rerun",
        selection_mode="single-row",
        hide_index=True,
        width="stretch",
        height=height,
    )
    rows = event.selection.rows if event and event.selection else []
    st.caption("Select a row to drill through to Customer 360.")
    if rows:
        customer_id = str(frame.iloc[rows[0]]["customer_id"])
        st.session_state[nonce_key] = nonce + 1  # clear the selection on the next run
        customer_360_dialog(customer_id)


def export_button(frame: pd.DataFrame, file_name: str, label: str, key: str) -> None:
    """CSV export capped at 5,000 rows, labelled as synthetic data."""
    capped = frame.head(data.EXPORT_ROW_CAP).copy()
    capped.insert(0, "data_notice", "SYNTHETIC DATA - not real customers")
    st.download_button(
        f"{label} ({fmt_int(len(capped))} of {fmt_int(len(frame))} rows, cap 5,000, synthetic)",
        capped.to_csv(index=False).encode("utf-8"),
        file_name=file_name,
        mime="text/csv",
        key=key,
        icon=":material/download:",
    )


# ---------------------------------------------------------------------------
# Customer 360 (page 9 and the drill-through dialog)
# ---------------------------------------------------------------------------
def load_customer(customer_id: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Fetch one case row and its documents by exact CustomerID (parameterised)."""
    case = data.query("SELECT * FROM mart_case_detail WHERE customer_id = ?", (customer_id,))
    docs = data.query(
        "SELECT doc_type, verified, confidence, issue_country, expiry_date "
        "FROM mart_customer_docs WHERE customer_id = ? ORDER BY doc_type",
        (customer_id,),
    )
    return case, docs


def _rule_path(row: pd.Series) -> pd.DataFrame:
    """Evaluate the policy rules in order and show which fired and why."""
    steps = [
        ("R1 Sanctions screening", "Sanctioned?", bool(row.is_sanctioned), "Reject"),
        ("R2 PEP enhanced due diligence", "Politically exposed person?", bool(row.is_pep), "Enhanced Due Diligence"),
        ("R3 High-risk escalation", "Risk tier = High?", row.risk_category == "High", "EDD or Manual Review"),
        (
            "R4 Document sufficiency",
            f"Verified documents < 4? ({int(row.verified_docs)})",
            int(row.verified_docs) < 4,
            "Pending Documents",
        ),
        ("R5 Standard approval", "Otherwise", True, "Approve"),
    ]
    out, fired = [], False
    for rule, test, hit, outcome in steps:
        status = "not evaluated" if fired else ("FIRED" if hit else "passed")
        out.append({"rule": rule, "test": test, "result": status, "outcome if fired": outcome})
        fired = fired or hit
    return pd.DataFrame(out)


def render_customer_360(customer_id: str, key_prefix: str = "c360") -> None:
    """Profile card, documents, rule path, risk score and simulated timeline."""
    case, docs = load_customer(customer_id)
    if case.empty:
        st.warning(f"No customer found with ID {customer_id}. IDs look like C000123 (exact match).")
        return
    row = case.iloc[0]
    agree = "agrees" if bool(row.engine_agrees) else "DISAGREES"
    st.markdown(
        f"**{html.escape(customer_id)}** · case {html.escape(str(row.case_id))} · synthetic profile "
        f"(names and dates of birth are not published)"
    )
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Labelled decision", str(row.decision))
    c2.metric("Rule engine", str(row.engine_decision), help=f"Engine {agree} with the label.")
    c3.metric("Risk tier", str(row.risk_category))
    c4.metric("Verified documents", f"{int(row.verified_docs)} / 5")
    profile = pd.DataFrame(
        {
            "attribute": [
                "Country",
                "Occupation",
                "Account type",
                "Age band",
                "Income quintile",
                "PEP",
                "Sanctioned",
                "AML flag",
                "Identity verified",
                "Address verified",
                "Last review",
                "Review overdue",
            ],
            "value": [
                row.country,
                row.occupation,
                row.account_type,
                row.age_band,
                f"Q{int(row.income_quintile)}",
                _yn(row.is_pep),
                _yn(row.is_sanctioned),
                _yn(row.aml_flag),
                _yn(row.identity_verified),
                _yn(row.address_verified),
                str(pd.Timestamp(row.last_updated).date()),
                f"{_yn(row.review_overdue)} ({int(row.days_since_review)} days)",
            ],
        }
    )
    left, right = st.columns([1, 1.3])
    with left:
        st.markdown("**Profile card**")
        st.dataframe(profile, hide_index=True, width="stretch", height=455)
    with right:
        st.markdown("**The 5 documents** (OCR confidence; no OCR text is published)")
        st.dataframe(
            tidy(docs),
            hide_index=True,
            width="stretch",
            column_config={
                "confidence": st.column_config.ProgressColumn("confidence", min_value=0.0, max_value=1.0, format="%.2f")
            },
        )
        breaches = [
            name
            for name, flag in (
                ("identity", row.breach_approved_no_identity),
                ("address", row.breach_approved_no_address),
                ("missing document", row.breach_approved_missing_doc),
            )
            if bool(flag)
        ]
        if breaches:
            st.error(f"Control breach: approved despite failed {', '.join(breaches)} check.")
        else:
            st.success("No control breach recorded for this case.")
    st.markdown("**Rule path** (recovered policy, evaluated in precedence order)")
    st.dataframe(_rule_path(row), hide_index=True, width="stretch")

    score, parts = kpis.risk_score_breakdown(
        bool(row.is_sanctioned),
        bool(row.is_pep),
        str(row.risk_category),
        bool(row.identity_verified),
        bool(row.address_verified),
        int(row.verified_docs),
    )
    a, b = st.columns([1, 1.4])
    with a:
        st.markdown(f"**Additive risk score: {score} / 100**")
        if parts:
            fig = go.Figure(
                go.Bar(
                    x=[p for _, p in parts],
                    y=[n for n, _ in parts],
                    orientation="h",
                    marker_color=BAD,
                    text=[f"+{p}" for _, p in parts],
                    textposition="auto",
                    hovertemplate="%{y}: +%{x}<extra></extra>",
                )
            )
            fig.update_layout(
                height=60 + 34 * len(parts),
                yaxis=dict(autorange="reversed"),
                template="kyc_pbi",
                paper_bgcolor=TILE,
                plot_bgcolor=TILE,
            )
            st.plotly_chart(
                fig, key=f"{key_prefix}_score_{customer_id}", width="stretch", config=CHART_CONFIG, theme=None
            )
        else:
            st.write("No risk components present.")
        footnote(
            "Illustration only, not a calibrated model: sanction 100, PEP 30, High risk 25, identity "
            "unverified 10, address unverified 10, each unverified document 5, capped at 100."
        )
    with b:
        st.markdown(f"**Case timeline** {sim_pill()}", unsafe_allow_html=True)
        opened = pd.Timestamp(row.opened_date)
        closed = opened + pd.Timedelta(days=float(row.tat_days))
        timeline = pd.DataFrame(
            {
                "event": [
                    "Case opened",
                    "Assigned",
                    "Decision recorded" if not row.is_open else "Still open at AS_OF",
                    "SLA target",
                ],
                "when": [
                    opened.date(),
                    opened.date(),
                    closed.date(),
                    (opened + pd.Timedelta(days=int(row.sla_days))).date(),
                ],
                "detail": [
                    f"via {row.channel}",
                    str(row.assigned_to),
                    f"{fmt_days(float(row.tat_days))} turnaround",
                    f"{int(row.sla_days)} days · {'BREACHED' if bool(row.sla_breached) else 'met'}",
                ],
            }
        )
        st.dataframe(tidy(timeline), hide_index=True, width="stretch")
        footnote(SIM_NOTE)


def _yn(value: object) -> str:
    return "Yes" if bool(value) else "No"


@st.dialog("Customer 360 (drill-through)", width="large")
def customer_360_dialog(customer_id: str) -> None:
    """Drill-through dialog opened from any case table."""
    render_customer_360(customer_id, key_prefix="dlg")


def valid_customer_id(text: str) -> bool:
    """Exact CustomerID format check (C + 6 digits) before any query runs."""
    return bool(CUSTOMER_ID_RE.match(text.strip()))


def kpi_snapshot(filters: Filters) -> dict:
    """All headline KPIs for a filter state in one parameterised SQL statement."""
    where, params = data.where_clause(filters)
    select = ", ".join(f"{sql} AS {name}" for name, sql in kpis.KPI_SQL.items())
    frame = data.query(f"SELECT {select} FROM mart_case_detail {where}", params)
    return {k: (None if pd.isna(v) else v) for k, v in frame.iloc[0].to_dict().items()}


def previous_snapshot(filters: Filters) -> dict | None:
    """KPIs for the previous equal-length period (None when it has no cases)."""
    prev_start, prev_end = kpis.previous_period(filters.start, filters.end)
    prev = kpi_snapshot(filters.with_dates(prev_start, prev_end))
    return prev if prev.get("cases") else None


def headline_finding() -> None:
    """Render the lead finding over the full population (independent of slicers)."""
    full_start, full_end = data.date_bounds()
    overall = kpi_snapshot(Filters(full_start, full_end))
    headline(
        f"<b>Headline finding (all {fmt_int(overall['cases'])} cases):</b> the decision logic is sound "
        f"(<b>{fmt_pct(overall['engine_agreement'])}</b> rule-engine reconciliation) but the verification "
        f"controls are not enforced (<b>{fmt_pct(overall['control_breach_rate'])}</b> of approvals carry a "
        "failed identity or address flag). This is a <b>control gap, not a logic error</b>."
    )


def kpi_delta(name: str, now: dict, prev: dict | None) -> float | None:
    """Period-over-period delta for one KPI."""
    if prev is None:
        return None
    return kpis.period_delta(now.get(name), prev.get(name))


def good_bad_color(ok: bool) -> str:
    """Green when good, red when bad."""
    return GOOD if ok else BAD


__all__ = ["TEAL", "fmt_days", "fmt_int", "fmt_pct"]
